using System.Collections.Generic;
using System.Linq;
using CultivationGame.Data;
using CultivationGame.Player;
using CultivationGame.Systems;
using CultivationGame.UI;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.InputSystem;

namespace CultivationGame.Editor
{
    public static class InspectorAutoSetup
    {
        private const string InputRefsFolder = "Assets/_Project/Input/AutoGenerated";

        [MenuItem("Tools/Cultivation/Auto Setup/Run Full Setup (Realms + Inspector)")]
        public static void RunFullSetup()
        {
            RealmProgressionLinker.LinkRealmProgression();
            RunSetup(fix: true);
        }

        [MenuItem("Tools/Cultivation/Auto Setup/Validate Inspector Setup")]
        public static void ValidateInspectorSetup()
        {
            RunSetup(fix: false);
        }

        [MenuItem("Tools/Cultivation/Auto Setup/Fix Inspector Setup")]
        public static void FixInspectorSetup()
        {
            RunSetup(fix: true);
        }

        private static void RunSetup(bool fix)
        {
            if (Application.isPlaying)
            {
                Debug.LogWarning("Inspector auto setup: stop Play Mode first.");
                return;
            }

            int fixedCount = 0;
            int issueCount = 0;

            InputActionAsset inputAsset = FindFirstAsset<InputActionAsset>();
            BuildMenuDataSource buildMenuData = FindFirstAsset<BuildMenuDataSource>();
            RecipeDatabase recipeDb = FindFirstAsset<RecipeDatabase>();

            var allRealms = FindAllAssets<RealmDefinition>().OrderBy(r => r.realmIndex).ToList();
            var allItems = FindAllAssets<ItemData>().OrderBy(i => i.name).ToList();

            InputActionReference playerInteractRef = GetOrCreateActionRef(inputAsset, "Player", "Interact", fix);
            InputActionReference buildPlaceRef = GetOrCreateActionRef(inputAsset, "BuildMode", "Place", fix);
            InputActionReference buildCancelRef = GetOrCreateActionRef(inputAsset, "BuildMode", "Cancel", fix);
            InputActionReference buildRotateRef = GetOrCreateActionRef(inputAsset, "BuildMode", "Rotate", fix);
            InputActionReference uiPauseRef = GetOrCreateActionRef(inputAsset, "UI", "Pause", fix);
            InputActionReference uiInventoryRef = GetOrCreateActionRef(inputAsset, "UI", "Inventory", fix);

            BuildGrid buildGrid = Object.FindFirstObjectByType<BuildGrid>();
            PlacementController placement = Object.FindFirstObjectByType<PlacementController>();
            PlayerInventory playerInventory = Object.FindFirstObjectByType<PlayerInventory>();
            PlayerStats playerStats = Object.FindFirstObjectByType<PlayerStats>();
            Camera anyCamera = Camera.main != null ? Camera.main : Object.FindFirstObjectByType<Camera>();
            var rb = playerStats != null ? playerStats.GetComponent<Rigidbody>() : null;

            if (placement != null)
            {
                var so = new SerializedObject(placement);
                ApplyObject(so, "buildGrid", buildGrid, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "playerInventory", playerInventory, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "buildCamera", anyCamera, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "placeAction", buildPlaceRef, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "cancelAction", buildCancelRef, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "rotateAction", buildRotateRef, ref fixedCount, ref issueCount, fix);

                // Best-effort: removal action is optional in current input asset.
                InputActionReference removeRef = GetOrCreateActionRef(inputAsset, "BuildMode", "Remove", fix);
                if (removeRef != null)
                    ApplyObject(so, "removeAction", removeRef, ref fixedCount, ref issueCount, fix);

                ApplyLayerMask(so, "terrainLayer", "Terrain", ref fixedCount, ref issueCount, fix);
                ApplyLayerMask(so, "machineLayer", "Machine", ref fixedCount, ref issueCount, fix);
                Commit(so, fix, placement);
            }

            foreach (var controller in Object.FindObjectsByType<BuildMenuController>(FindObjectsSortMode.None))
            {
                var so = new SerializedObject(controller);
                ApplyObject(so, "buildMenuData", buildMenuData, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "placementController", placement, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "playerInventory", playerInventory, ref fixedCount, ref issueCount, fix);
                Commit(so, fix, controller);
            }

            foreach (var inspect in Object.FindObjectsByType<MachineInspectUI>(FindObjectsSortMode.None))
            {
                var so = new SerializedObject(inspect);
                ApplyObject(so, "recipeDatabase", recipeDb, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "playerInventory", playerInventory, ref fixedCount, ref issueCount, fix);
                Commit(so, fix, inspect);
            }

            foreach (var interactor in Object.FindObjectsByType<PlayerInteractor>(FindObjectsSortMode.None))
            {
                var so = new SerializedObject(interactor);
                ApplyObject(so, "interactAction", playerInteractRef, ref fixedCount, ref issueCount, fix);
                ApplyLayerMask(so, "interactableLayer", "Interactable", ref fixedCount, ref issueCount, fix);
                Commit(so, fix, interactor);
            }

            foreach (var gsm in Object.FindObjectsByType<GameStateManager>(FindObjectsSortMode.None))
            {
                var so = new SerializedObject(gsm);
                ApplyObject(so, "pauseAction", uiPauseRef, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "toggleInventoryAction", uiInventoryRef, ref fixedCount, ref issueCount, fix);
                Commit(so, fix, gsm);
            }

            foreach (var camSystem in Object.FindObjectsByType<CameraSystem>(FindObjectsSortMode.None))
            {
                var so = new SerializedObject(camSystem);
                ApplyObject(so, "inputActions", inputAsset, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "playerStats", playerStats, ref fixedCount, ref issueCount, fix);
                if (playerStats != null)
                    ApplyObject(so, "playerTransform", playerStats.transform, ref fixedCount, ref issueCount, fix);
                Commit(so, fix, camSystem);
            }

            foreach (var bt in Object.FindObjectsByType<BreakthroughSystem>(FindObjectsSortMode.None))
            {
                var so = new SerializedObject(bt);
                ApplyObject(so, "playerStats", playerStats, ref fixedCount, ref issueCount, fix);
                Commit(so, fix, bt);
            }

            foreach (var save in Object.FindObjectsByType<SaveManager>(FindObjectsSortMode.None))
            {
                var so = new SerializedObject(save);
                ApplyObject(so, "playerStats", playerStats, ref fixedCount, ref issueCount, fix);
                ApplyObject(so, "playerInventory", playerInventory, ref fixedCount, ref issueCount, fix);
                if (playerStats != null)
                {
                    ApplyObject(so, "playerTransform", playerStats.transform, ref fixedCount, ref issueCount, fix);
                    ApplyObject(so, "playerRigidbody", rb, ref fixedCount, ref issueCount, fix);
                }
                ApplyObjectList(so, "allRealms", allRealms.Cast<Object>().ToList(), ref fixedCount, ref issueCount, fix);
                ApplyObjectList(so, "allItems", allItems.Cast<Object>().ToList(), ref fixedCount, ref issueCount, fix);
                Commit(so, fix, save);
            }

            if (fix)
            {
                EditorSceneManager.MarkAllScenesDirty();
                AssetDatabase.SaveAssets();
            }

            string mode = fix ? "Fix" : "Validate";
            Debug.Log($"Inspector auto setup ({mode}): issues={issueCount}, fixed={fixedCount}.");
        }

        private static T FindFirstAsset<T>() where T : Object
        {
            string[] guids = AssetDatabase.FindAssets($"t:{typeof(T).Name}");
            if (guids == null || guids.Length == 0) return null;

            string path = AssetDatabase.GUIDToAssetPath(guids[0]);
            return AssetDatabase.LoadAssetAtPath<T>(path);
        }

        private static List<T> FindAllAssets<T>() where T : Object
        {
            var result = new List<T>();
            string[] guids = AssetDatabase.FindAssets($"t:{typeof(T).Name}");
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                var asset = AssetDatabase.LoadAssetAtPath<T>(path);
                if (asset != null) result.Add(asset);
            }
            return result;
        }

        private static InputActionReference GetOrCreateActionRef(InputActionAsset asset, string mapName, string actionName, bool fix)
        {
            if (asset == null) return null;

            InputActionMap map = asset.FindActionMap(mapName, throwIfNotFound: false);
            InputAction action = map?.FindAction(actionName, throwIfNotFound: false);
            if (action == null) return null;

            string safeName = $"{mapName}_{actionName}";
            string path = $"{InputRefsFolder}/{safeName}.asset";

            var existing = AssetDatabase.LoadAssetAtPath<InputActionReference>(path);
            if (existing != null)
                return existing;

            if (!fix)
                return null;

            if (!AssetDatabase.IsValidFolder(InputRefsFolder))
            {
                string[] segments = InputRefsFolder.Split('/');
                string current = segments[0];
                for (int i = 1; i < segments.Length; i++)
                {
                    string next = current + "/" + segments[i];
                    if (!AssetDatabase.IsValidFolder(next))
                        AssetDatabase.CreateFolder(current, segments[i]);
                    current = next;
                }
            }

            var created = InputActionReference.Create(action);
            AssetDatabase.CreateAsset(created, path);
            AssetDatabase.ImportAsset(path);
            return created;
        }

        private static void ApplyObject(SerializedObject so, string propertyName, Object desired, ref int fixedCount, ref int issueCount, bool fix)
        {
            SerializedProperty prop = so.FindProperty(propertyName);
            if (prop == null) return;

            if (desired == null)
            {
                if (prop.objectReferenceValue == null) return;
                issueCount++;
                return;
            }

            if (prop.objectReferenceValue == desired) return;

            issueCount++;
            if (!fix) return;

            prop.objectReferenceValue = desired;
            fixedCount++;
        }

        private static void ApplyObjectList(SerializedObject so, string propertyName, List<Object> desired, ref int fixedCount, ref int issueCount, bool fix)
        {
            SerializedProperty prop = so.FindProperty(propertyName);
            if (prop == null || !prop.isArray) return;

            bool identical = prop.arraySize == desired.Count;
            if (identical)
            {
                for (int i = 0; i < desired.Count; i++)
                {
                    if (prop.GetArrayElementAtIndex(i).objectReferenceValue != desired[i])
                    {
                        identical = false;
                        break;
                    }
                }
            }

            if (identical) return;

            issueCount++;
            if (!fix) return;

            prop.arraySize = desired.Count;
            for (int i = 0; i < desired.Count; i++)
                prop.GetArrayElementAtIndex(i).objectReferenceValue = desired[i];
            fixedCount++;
        }

        private static void ApplyLayerMask(SerializedObject so, string propertyName, string expectedLayerName, ref int fixedCount, ref int issueCount, bool fix)
        {
            int layer = LayerMask.NameToLayer(expectedLayerName);
            if (layer < 0) return;

            SerializedProperty prop = so.FindProperty(propertyName);
            if (prop == null) return;

            int expectedMask = 1 << layer;
            int currentMask = prop.intValue;

            // Treat missing expected layer bit as misconfigured.
            if ((currentMask & expectedMask) != 0) return;

            issueCount++;
            if (!fix) return;

            prop.intValue = expectedMask;
            fixedCount++;
        }

        private static void Commit(SerializedObject so, bool fix, Object target)
        {
            if (!fix) return;
            if (!so.hasModifiedProperties) return;

            Undo.RecordObject(target, "Auto Inspector Setup");
            so.ApplyModifiedProperties();
            EditorUtility.SetDirty(target);
        }
    }
}